version: '3'

services:
  asurada-app:
    build: .
    container_name: asurada-app
    volumes:
      - .:/app
      - ./assets:/app/assets
      - ./uploads:/app/uploads
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: python api_server.py
    restart: unless-stopped
    environment:
      - PORT=8000
      - DEBUG=True 